const reportsystemroute = (app, dynamicWrapper) => ({
  '/HdDls': { component: dynamicWrapper(app, [], () => import('../routes/HdDls')), },
  '/HdDls/list': { component: dynamicWrapper(app, [], () => import('../routes/HdDls/List')), },
  '/HdDls/info': { component: dynamicWrapper(app, [], () => import('../routes/HdDls/Info')), },
  '/HdDz': { component: dynamicWrapper(app, [], () => import('../routes/HdDz')), },
  '/HdDz/list': { component: dynamicWrapper(app, [], () => import('../routes/HdDz/List')), },
  '/HdDz/info': { component: dynamicWrapper(app, [], () => import('../routes/HdDz/Info')), },
  '/HdHuodong': { component: dynamicWrapper(app, [], () => import('../routes/HdHuodong')), },
  '/HdHuodong/list': { component: dynamicWrapper(app, [], () => import('../routes/HdHuodong/List')), },
  '/HdHuodong/info': { component: dynamicWrapper(app, [], () => import('../routes/HdHuodong/Info')), },
  '/HdHuodong2shop': { component: dynamicWrapper(app, [], () => import('../routes/HdHuodong2shop')), },
  '/HdHuodong2shop/list': { component: dynamicWrapper(app, [], () => import('../routes/HdHuodong2shop/List')), },
  '/HdHuodong2shop/info': { component: dynamicWrapper(app, [], () => import('../routes/HdHuodong2shop/Info')), },
  '/HdHuodong2user': { component: dynamicWrapper(app, [], () => import('../routes/HdHuodong2user')), },
  '/HdHuodong2user/list': { component: dynamicWrapper(app, [], () => import('../routes/HdHuodong2user/List')), },
  '/HdHuodong2user/info': { component: dynamicWrapper(app, [], () => import('../routes/HdHuodong2user/Info')), },
  '/HdShop': { component: dynamicWrapper(app, [], () => import('../routes/HdShop')), },
  '/HdShop/list': { component: dynamicWrapper(app, [], () => import('../routes/HdShop/List')), },
  '/HdShop/info': { component: dynamicWrapper(app, [], () => import('../routes/HdShop/Info')), },
  '/HdShopuser': { component: dynamicWrapper(app, [], () => import('../routes/HdShopuser')), },
  '/HdShopuser/list': { component: dynamicWrapper(app, [], () => import('../routes/HdShopuser/List')), },
  '/HdShopuser/info': { component: dynamicWrapper(app, [], () => import('../routes/HdShopuser/Info')), },
  '/HdUser': { component: dynamicWrapper(app, [], () => import('../routes/HdUser')), },
  '/HdUser/list': { component: dynamicWrapper(app, [], () => import('../routes/HdUser/List')), },
  '/HdUser/info': { component: dynamicWrapper(app, [], () => import('../routes/HdUser/Info')), },
  '/HdZone': { component: dynamicWrapper(app, [], () => import('../routes/HdZone')), },
  '/HdZone/list': { component: dynamicWrapper(app, [], () => import('../routes/HdZone/List')), },
  '/HdZone/info': { component: dynamicWrapper(app, [], () => import('../routes/HdZone/Info')), },
  '/shopsaoma': { component: dynamicWrapper(app, [], () => import('../routes/saoma')), },
  '/shopinfo': { component: dynamicWrapper(app, [], () => import('../routes//HdShop/infoindex')), },
  '/shopuserinfo': { component: dynamicWrapper(app, [], () => import('../routes//HdShopuser/infoindex')), },
  '/HdBaoming':{  component: dynamicWrapper(app, [], () => import('../routes/HdBaoming')),  },
  '/HdBaoming/list': {  component: dynamicWrapper(app, [], () => import('../routes/HdBaoming/List')),  },
  '/HdBaoming/info': {  component: dynamicWrapper(app, [], () => import('../routes/HdBaoming/Info')),  },
});

export default reportsystemroute;
